FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
COPY dashboard_agua.py .

RUN pip install --no-cache-dir streamlit pandas

EXPOSE 8501

CMD ["streamlit", "run", "dashboard_agua.py", "--server.port=8501", "--server.address=0.0.0.0"]

